"""
CloudShield IQ — Grounded Explanation Schemas
==============================================
Pydantic v2 schemas for the Grounded LLM Explanation Architecture.
Enforces strict boundaries between probabilistic ML, deterministic compliance,
and evidence-grounded human-readable explanations.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Optional
from pydantic import BaseModel, Field


class EvidencePack(BaseModel):
    """
    Validated Evidence Package consumed by the LLM explanation service.
    Aggregates verified telemetry, ML anomaly scores, SHAP factors, compliance violations,
    and remediation guidance into a tamper-resistant factual envelope.
    """
    finding_id: str = Field(..., description="Unique finding or assessment identifier")
    title: str = Field(..., description="Canonical security finding title")
    cloud_provider: str = Field(..., description="AWS, Azure, or GCP")
    resource_id: str = Field(..., description="Cloud resource identifier or ARN")
    resource_type: Optional[str] = Field(None, description="Resource classification type")
    severity: str = Field(..., description="Severity tier: CRITICAL, HIGH, MEDIUM, LOW")
    risk_score: float = Field(..., ge=0.0, le=100.0, description="Composite calibrated risk score")
    category: str = Field(..., description="Security domain: IAM, Storage, Network, Crypto, etc.")
    
    # Behavioral & Contextual Telemetry Evidence
    mfa_used: Optional[bool] = Field(None, description="Whether multi-factor authentication was present")
    actor_type: Optional[str] = Field(None, description="Principal type: root, user, assumed_role, service_account")
    actor_name: Optional[str] = Field(None, description="Identifier of the executing identity")
    action: Optional[str] = Field(None, description="Canonical cloud API action executed")
    source_ip: Optional[str] = Field(None, description="Originating client IP address")
    region: Optional[str] = Field(None, description="Cloud region where action took place")

    # Machine Learning & Explainability Evidence
    anomaly_detected: Optional[bool] = Field(None, description="Whether Isolation Forest flagged anomalous activity")
    anomaly_score: Optional[float] = Field(None, ge=0.0, le=1.0, description="Unsupervised anomaly probability")
    shap_top_feature: Optional[str] = Field(None, description="Highest contributing risk driver feature name")
    shap_impact: Optional[float] = Field(None, description="SHAP numerical contribution delta")
    shap_factors: list[dict[str, Any]] = Field(default_factory=list, description="Top SHAP feature attributions")

    # Deterministic Compliance Evidence
    compliance_violations: list[str] = Field(default_factory=list, description="Codified regulatory controls violated")

    # Verified Remediation Guidance
    remediation_guidance: str = Field(..., description="Prescribed remediation workflow")
    cli_remediation_command: Optional[str] = Field(None, description="Vendor CLI execution command")
    terraform_remediation_snippet: Optional[str] = Field(None, description="Declarative Infrastructure-as-Code patch")


class SecurityExplanation(BaseModel):
    """
    Structured human-readable explanation produced by the explanation service.
    Strictly grounded in the supplied EvidencePack; zero hallucinations.
    """
    finding_id: str = Field(..., description="Reference finding identifier")
    risk: str = Field(..., description="Verified severity tier (CRITICAL, HIGH, MEDIUM, LOW)")
    what_happened: str = Field(..., description="Factual description of the security activity grounded in evidence")
    why_it_matters: str = Field(..., description="Operational security risk and baseline deviation rationale")
    evidence: list[str] = Field(default_factory=list, description="Bulleted list of verified factual telemetry points")
    compliance_impact: str = Field(..., description="Statutory compliance controls violated and audit impact")
    recommended_action: str = Field(..., description="Actionable, non-destructive remediation advice")
    grounding_score: float = Field(1.0, ge=0.0, le=1.0, description="Metric confirming 100% evidence grounding")
    is_llm_generated: bool = Field(False, description="True if generated by LLM; False if produced by deterministic engine")
    generated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    model_used: Optional[str] = Field(None, description="LLM model name or 'deterministic-grounded-engine'")
